export const productData = [{
    brand: "AHIKA",
    productDescription: 'Women Black & Green Printed Straight Kurta',
    actualPrice: '1350',
    discountedPrice: '688',
    productImage: 'https://rukminim1.flixcart.com/image/580/696/l33cia80/kurta/e/b/g/s-libaas-101-auriprx-fashion-original-imageantzs7smtae.jpeg?q=50',
    rating: '4',
    reviews: '19.6',
},
{
    brand: "Khushal K",
    productDescription: 'Women Black Ethnic Motifs Printed Kurta with Palazzos & With Dupatta',
    actualPrice: '5099',
    discountedPrice: '1427',
    productImage: 'https://rukminim1.flixcart.com/image/580/696/l33cia80/kurta/e/b/g/s-libaas-101-auriprx-fashion-original-imageantzs7smtae.jpeg?q=50',
    rating: '4.4',
    reviews: '3.5',
},
{
    brand: "METRONAUT By Flipkart ",
    productDescription: 'Men Regular Fit Checkered Spread Collar Casual Shirt',
    actualPrice: '1299',
    discountedPrice: '454',
    productImage: 'https://rukminim1.flixcart.com/image/880/1056/kzzw5u80/shirt/v/h/l/m-mss21eppsh1061b-metronaut-original-imagbvr7y4kwxrda.jpeg?q=50',
    rating: '4',
    reviews: '51',
},
{
    brand: "METRONAUT By Flipkart ",
    productDescription: 'Slim Men Light Blue Jeans',
    actualPrice: '2199',
    discountedPrice: '525',
    productImage: 'https://rukminim1.flixcart.com/image/880/1056/kvgzyq80/jean/m/w/2/32-maw21jn806-metronaut-original-imag8da5hbff7rmp.jpeg?q=50',
    rating: '3.8',
    reviews: '179',
},
{
    brand: "WOODLAND",
    productDescription: 'Leather Casual For Men  (Olive)',
    actualPrice: '3595',
    discountedPrice: '3055',
    productImage: 'https://rukminim1.flixcart.com/image/880/1056/kiqbma80-0/shoe/p/y/j/gc-1759115-39-woodland-camel-original-imafygsbemghgbcc.jpeg?q=50',
    rating: '4.1',
    reviews: '7454',
},
{
    brand: "PUMA",
    productDescription: 'Puma Smash v2 L Sneakers For Men  (White)',
    actualPrice: '3576',
    discountedPrice: '1575',
    productImage: 'https://rukminim1.flixcart.com/image/880/1056/l41n2q80/shoe/c/f/d/-original-imagfywbpbm62u3h.jpeg?q=50',
    rating: '3.1',
    reviews: '',
},
{
    brand: "PROVOGUE",
    productDescription: 'Men Regular Fit Checkered Casual Shirt',
    actualPrice: '1999',
    discountedPrice: '659',
    productImage: 'https://rukminim1.flixcart.com/image/880/1056/l0jwbrk0/shirt/t/x/j/m-praw21csh032b-provogue-original-imagcbcfxhhqsvff.jpeg?q=50',
    rating: '4.2',
    reviews: '564',
},
{
    brand: "Noise",
    productDescription: 'Noise ColorFit Caliber Smartwatch  (Black Strap, Regular)',
    actualPrice: '3999',
    discountedPrice: '1799',
    productImage: 'https://rukminim1.flixcart.com/image/416/416/ky0g58w0/smartwatch/o/n/8/-original-imagac74kujhzzrc.jpeg?q=70',
    rating: '4.2',
    reviews: '58665',
},
]
